FIGURES_PDF =	zfs_label.pdf			\
		zfs_blkptr.pdf			\
		zfs_embedded_blkptr.pdf		\
		zfs_vdev.pdf			\
		zfs_vdev_label.pdf		\
		zfs_vdev_tree.pdf		\
		zfs_ub.pdf			\
		zfs_ub_expanded.pdf		\
		zfs_mos.pdf			\
		zfs_fs.pdf			\
		zfs_indirect.pdf		\
		zfs_dsl_infra.pdf		\
		zfs_dnode_phys.pdf		\
		zfs_3levels.pdf			\
		zfs_objset_phys.pdf		\
		zfs_objset.pdf			\
		zfs_ondisk_mos.pdf		\
		zfs_mzap.pdf			\
		zfs_fzap_overview.pdf		\
		zfs_zap_phys.pdf		\
		zfs_zap_leaf.pdf		\
		zfs_zil_structure.pdf
